<?php

$produtos = array(
    0 => array('nome'=>'MACACO #1', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco1.png'),
    1 => array('nome'=>'MACACO #2', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco2.png'),
    2 => array('nome'=>'MACACO #3', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco3.png'),
    3 => array('nome'=>'MACACO #4', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco4.png'),
    4 => array('nome'=>'MACACO #5', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco5.png'),
    5 => array('nome'=>'MACACO #6', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco6.png'),
    6 => array('nome'=>'MACACO #7', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco7.png'),
    7 => array('nome'=>'MACACO #8', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco8.png'),
    8 => array('nome'=>'MACACO #9', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco9.png'),
    9 => array('nome'=>'MACACO #10', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco10.png'),
    10 => array('nome'=>'MACACO #11', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco11.png'),
    11 => array('nome'=>'MACACO #12', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco12.png'),
    12 => array('nome'=>'MACACO #13', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco13.png'),
    13 => array('nome'=>'MACACO #14', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco14.png'),
    14 => array('nome'=>'MACACO #15', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco15.png'),
    15 => array('nome'=>'MACACO #16', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco16.png'),
    16 => array('nome'=>'MACACO #17', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco17.png'),
    17 => array('nome'=>'MACACO #18', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco18.png'),
    18 => array('nome'=>'MACACO #19', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco19.png'),
    19 => array('nome'=>'MACACO #20', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco20.png'),
    20 => array('nome'=>'MACACO #21', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco21.png'),
    21 => array('nome'=>'MACACO #22', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco22.png'),
    22 => array('nome'=>'MACACO #23', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco23.png'),
    23 => array('nome'=>'MACACO #24', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco24.png'),
    24 => array('nome'=>'MACACO #25', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco25.png'),
    25 => array('nome'=>'MACACO #26', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco26.png'),
    26 => array('nome'=>'MACACO #27', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco27.png'),
    27 => array('nome'=>'MACACO #28', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco28.png'),
    28 => array('nome'=>'MACACO #29', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco29.png'),
    29 => array('nome'=>'MACACO #30', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco30.png'),
    30 => array('nome'=>'MACACO #31', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco31.png'),
    31 => array('nome'=>'MACACO #32', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco32.png'),
    32 => array('nome'=>'MACACO #33', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco33.png'),
    33 => array('nome'=>'MACACO #34', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco34.png'),
    34 => array('nome'=>'MACACO #35', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco35.png'),
    35 => array('nome'=>'MACACO #36', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco36.png'),
    36 => array('nome'=>'MACACO #37', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco37.png'),
    37 => array('nome'=>'MACACO #38', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco38.png'),
    38 => array('nome'=>'MACACO #39', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco39.png'),
    39 => array('nome'=>'MACACO #40', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco40.png'),
    40 => array('nome'=>'MACACO #41', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco41.png'),
    41 => array('nome'=>'MACACO #42', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco42.png'),
    42 => array('nome'=>'MACACO #43', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco43.png'),
    43 => array('nome'=>'MACACO #44', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco44.png'),
    44 => array('nome'=>'MACACO #45', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco45.png'),
    45 => array('nome'=>'MACACO #46', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco46.png'),
    46 => array('nome'=>'MACACO #47', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco47.png'),
    47 => array('nome'=>'MACACO #48', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco48.png'),
    48 => array('nome'=>'MACACO #49', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco49.png'),
    49 => array('nome'=>'MACACO #50', 'preco'=>'R$ 1.000,00', 'descricao'=>'MACACO LEGAL', 'imagem'=>'macaco50.png'),
)
?>